# Կայքի հիմնական տվյալներ
site_name: Ձեր անունը - Fab Academy
site_description: Fab Academy փաստաթղթավորման կայք՝ Ձեր անվան համար
site_author: Ձեր անունը
copyright: Հեղինակային իրավունք 2026 Ձեր անունը - Creative Commons Attribution Non Commercial

site_url: http://fibasile.fabcloud.io/fabacademy-student-template/

extra:
  # Ավելացրեք Ձեր սոցիալական ցանցերը ստորև (կամ հեռացրեք)
  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/fabacademany
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/fabacademany
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fabacademany
    - icon: fontawesome/brands/linkedin
      link: "https://linkedin.com/in/academany"

theme:
  name: material
  language: hy
  palette:
    - scheme: slate
      primary: amber
      accent: yellow
      toggle:
        icon: material/weather-night
        name: Անցնել դեպի լուսավոր ռեժիմ
    - scheme: default
      primary: amber
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Անցնել դեպի մուգ ռեժիմ
  font:
    text: Noto Sans Armenian
    code: Ubuntu Mono
  icon:
    logo: material/school
  favicon: images/favicon.svg
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.top
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: hy
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, False]

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      title: Բովանդակություն