
site_name: Ալեքս - Ֆաբ Դպրոց
site_description: Ֆաբ Դպրոցի ուսանողների համար նախատեսված կայքի ձևանմուշ
site_author: Ալեքս
copyright: Copyright 2026 Ալեքս
site_url: http://fibasile.fabcloud.io/fabacademy-student-template/
extra:

  # Set your own social media below (or remove)

  social:

    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/

    - icon: fontawesome/brands/instagram

      link: https://instagram.com/fabacademany

    - icon: fontawesome/brands/facebook

      link: https://facebook.com/fabacademany

    - icon: fontawesome/brands/twitter

      link: https://twitter.com/fabacademany

    - icon: fontawesome/brands/linkedin

      link: "https://linkedin.com/in/academany"



theme:

  name: material

  palette:

    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors

    primary: amber

    accent: orange

  font:

    # See available fonts at https://fonts.google.com/

    text: Ubuntu

    code: Ubuntu Mono

  icon:

    logo: material/school

  favicon: images/favicon.svg

  features:

    - navigation.tabs

    - navigation.instant



plugins:

  - search

  - git-revision-date-localized:

      fallback_to_build_date: true

      # Read more: https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/#enabled

      enabled: !ENV [ENABLED_GIT_REVISION_DATE, False]



markdown_extensions:

  - extra

  - smarty

  - admonition

  - codehilite:

      guess_lang: false

  - toc:

      permalink: true 

nav:

  - Գլխավոր էջ: index.md
  - About me: About me/index.md
  - Exercises: Exercises/
      - Շաբաթ 1: Շաբաթ 1.md
      - Շաբաթ 2: Շաբաթ 2.md
      - Շաբաթ 3: Շաբաթ 3.md
      - Շաբաթ 4: Շաբաթ 4.md
      - Շաբաթ 5: Շաբաթ 5.md
      - Շաբաթ 6: Շաբաթ 6.md
  - Projects: Projects/final-project.md
